### ISSUE TITLE
[Kicker]: "forget documents/apps" not working correctly

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#117] opened 2015-05-11 19:01 UTC
to test:
delete an entry via "forget document", then its gone
choose option "forget all documents", then the menu closes and after looking again the previously "forgotten" document is restores again

**Comment by eikehein** [comment] 2015-05-11 19:08
We noticed this the other day when fixing fixing the item count limit and it's already fixed on the 5.3 branch:

http://quickgit.kde.org/?p=plasma-desktop.git&a=commit&h=b05b5dcdbf135a54066ba3a75f636cdebf0b89c7
http://quickgit.kde.org/?p=plasma-desktop.git&a=commit&h=b58c0b32fad13f7a183bb2473323849a5c12e99a
http://quickgit.kde.org/?p=plasma-desktop.git&a=commit&h=b8c363200cf075cb54ffea794d2608737a06449a

**Comment by star-buck** [comment] 2015-05-13 12:10
@apachelogger : can you package this?

**Comment by apachelogger** [comment] 2015-05-13 12:39
1 out of 1 hunk FAILED -- rejects in file applets/kicker/plugin/recentcontactsmodel.cpp
:unamused:

**Comment by eikehein** [comment] 2015-05-13 12:43
What does it reject? There were two patches to recentcontactsmodel.cpp since early April and they're both in the list above. Maybe you went with the wrong apply order?

**Comment by apachelogger** [comment] 2015-05-13 12:54
@eikehein indeed. it's supposed to be b58c0b32fad13f7a183bb2473323849a5c12e99a -> b05b5dcdbf135a54066ba3a75f636cdebf0b89c7 -> b8c363200cf075cb54ffea794d2608737a06449a

**Comment by apachelogger** [comment] 2015-05-13 13:15
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-updates/+sourcepub/5063425/+listing-archive-extra

**Comment by star-buck** [comment] 2015-05-13 19:19
installed all updated packages and now it does leave all documents / apps visible even after removing:
https://www.dropbox.com/s/2apchrzu8i28hzt/kicker-recent-not-removed.mkv?dl=0

The menu then no longer adds new recent documents/apps entries, and only after a logout/login the gets updated and the documents/apps forgotten are no longer shown.

**Comment by eikehein** [comment] 2015-05-13 19:25
I'm afraid it works completely fine here. @ivan-cukic, can you think of any missed patches, or could the activities DB have been corrupted somehow? (Kicker just calls a method on the kactivities code.)

**Comment by ivan-cukic** [comment] 2015-05-13 19:29
Can we get an ISO with this so that I can test?

**Comment by ivan-cukic** [comment] 2015-05-13 19:36
(I can use the last iso and upgrade ofc, but I'd rather like to start with a clean slate)

**Comment by star-buck** [comment] 2015-05-13 19:37
sure, here is the last build (maybe something was packaged wrong or interfered with other patches/fixes/customization):
http://dev.netrunner.com/dev/netrunner-16-dvd-64bit-build3-150513-1645.iso

**Comment by ivan-cukic** [comment] 2015-05-13 21:32
@apachelogger Is it possible to ship kactivities 5.10 instead of 5.9? There were a few changes to the kamd plugin that handles the statistics - mainly the changes to the dbus communication between the service and the library that were needed by the stats library.

(It should be buildable with KF5.9 - just lower the KF5_DEP_VERSION in the CMakeLists.txt)

**Comment by star-buck** [comment] 2015-05-13 21:42
@apachelogger : any way to package kf5.10? We could use this ppa for testing:
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-kf5-10

**Comment by star-buck** [comment] 2015-05-14 11:41
@ivan-cukic : if not possible to ship kf5.10 (we like to release on the weekend):
Which package(s) would be needed to update?
I could also try out another kf-version of that package from kci?

**Comment by ivan-cukic** [comment] 2015-05-14 12:20
I've build kactivities (5.10) on netrunner and the recent applications are deleted correctly.

It also seems to be working for the recent documents (tested gwenview since kate and friends with kactivities support have not been released yet).

**Comment by star-buck** [comment] 2015-05-14 13:19
I updated kactivities-kf5 to this packages: https://launchpad.net/~kubuntu-ci/+archive/ubuntu/unstable-daily/+sourcepub/5065133/+listing-archive-extra
That was the latest I found for Kubuntu "vivid".
Now it works much better, still not perfect:
https://www.dropbox.com/s/dstdje1v9l6oged/kicker-recent-docs.mkv?dl=0

So deleting single items works, whereas "Forget all" also emptys the other Recent Items (in this case documents).

Not sure if a newer version would fix this, if some other package is needed or if kicker patch needs an update.

Also one suggestion for improvement: 
Can we keep the menu open also after "Forget all" and the submenu simply gets shown empty, that would be better because the user would 
a) immediatly get a feedback it has worked like when deleting a single item, so he doesnt need to reopen and see if it is really empty (and one always would if its important, just to confirm) and
b) also you can continue right away to the next Recent menu section and delete something there or do something else while you're already at the menu.

**Comment by eikehein** [comment] 2015-05-14 13:29
> Not sure if a newer version would fix this, if some other package is needed or if kicker patch needs an update.

The Kicker side to the "Forget All" part is really boring: It calls a method on the model provided by the activities lib. Nothing in the code that would cause the above.

About the suggestion, empty categories are already shown greyed out, so instead of showing a buggy empty submenu, I'd suggest closing just the submenu. The immediate feedback is then the greyed out category name.

**Comment by ivan-cukic** [comment] 2015-05-14 13:33
It is still not 5.10. The packages that need to be updated are all that are built from the kactivities source package (at least libkactivities6, kactivities - I guess these are the only packages built from kactivities @apachelogger ?)

**Comment by apachelogger** [comment] 2015-05-14 13:43
@ivan-cukic https://launchpad.net/~kubuntu-ci/+archive/ubuntu/unstable-daily/+sourcepub/5065133/+listing-archive-extra is a master build

**Comment by apachelogger** [comment] 2015-05-14 13:50
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-kf5-10/+sourcepub/5066993/+listing-archive-extra

**Comment by ivan-cukic** [comment] 2015-05-14 14:20
With the latest packages, it seems to be working. For me, at least.

@star-buck can you confirm?

**Comment by ivan-cukic** [comment] 2015-05-14 14:44
Just in case, I've done a clean install of NetRunner on a new VM, updated the two kactivities-related packages (just libkf5activities5 and kactivities), restarted. The document forgetting still works.

**Comment by star-buck** [comment] 2015-05-14 16:49
@eikehein : makes sense, so just closing the submenu but leaving main menu open would be fine.

**Comment by star-buck** [comment] 2015-05-14 17:05
@ivan-cukic : forced to reinstall now, updating blew my system in getting a black screen after login (not even krunner starts)... lets see that updating from a fresh installation works...

**Comment by star-buck** [comment] 2015-05-14 17:14
@ivan-cukic : I see the package does include also qml-module-org-kde-extensionplugin, and we cant really prevent people also updating that themselves next time... so can you confirm it either work also with updating that or @apachelogger has to make package based on frameworks 5.9.

About Recent documents: How do we get the information that some document was opened or edited in for example LibreOffice? Its doubtful that LibreOffice will adapt to kamd... so can we get the information what document was edited or opened from within Plasma (under Windows, even old programs like photshop6.0 from 2000 gets all recent documents listed, even if opened from within that program...).

**Comment by ivan-cukic** [comment] 2015-05-14 17:42
> package does include also qml-module-org-kde-extensionplugin, and we cant

Yes. I've tested with and without that package - it does not contain (almost) anything relevant to the recent documents.

> About Recent documents: How do we get the information that some document was 
> opened or edited in for example LibreOffice?

KAMD listens to changes in .local/share/RecentDocuments (or more precisely, it watches for the directory returned by KRecentDocument::recentDocumentDirectory()), so if an application supports the XDG spec for that, it will be supported. It should be populated every time someone clicks a file in dolphin or opens a file through kde's file dialogue.

Now, there is something wrong in NetRunner's setup - that directory remains empty.

Update:

After some digging, I realized the XDG Recent Documents reported by Dolphin go to ~/.kde/share/apps/RecentDocuments folder (dolphin 4.x with KRecentDocument library from 4.x), so it does not end up in kamd (which uses KRecentDocument library from 5.x).

This can be fixed simply by making ~/.kde/share/apps/RecentDocuments a symbolic link to ~/.local/share/RecentDocuments. But this needs to be done while setting up the account, or possibly on user log-in.

**Comment by ivan-cukic** [comment] 2015-05-14 17:44
As for the proper support for libreoffice, I guess it should be possible to do via an extension. LO has a nice C++/Java/.. extension mechanism that could possibly allow us to get the currently opened document.

**Comment by star-buck** [comment] 2015-05-14 17:57
@ivan-cukic : i updated to the latest packages and still have the same behaviour:
"Forget all" applications closes Kicker, and after reopening the formerly filled Recent Documents is also greyed out. After logout/login though, any Recent document is showing up again. Any idea or is it due to what you wrote above with the symlink?

**Comment by star-buck** [comment] 2015-05-14 17:59
@eikehein : can you change kicker behaviour to not close the entire menu when choosing "forget all"? Just leave the main menu open and Recent greyed out, pretty much like if you click "forget this single item" if only one entry remains under Recent applications for example.

**Comment by ivan-cukic** [comment] 2015-05-14 17:59
When you say 'showing up again' do you mean that the documents previously deleted are popping up again, or just the new documents are being added?

**Comment by star-buck** [comment] 2015-05-14 18:30
@ivan-cukic : in the video, there were 2 recent documents before both menus greyed out.
After logout/login, these document are shown again, so it was only the menu in a wrongly greyed out state I assume (the recent apps menu stays greyed out which is correct since all should have been forgotten). This behaviour basically didnt change with the kf5.10:
https://www.dropbox.com/s/dstdje1v9l6oged/kicker-recent-docs.mkv?dl=0

**Comment by ivan-cukic** [comment] 2015-05-14 19:08
I've managed to reproduce the issue.

It seems that the model in the plasma-desktop's version of KActivitiesStats is misbehaving. I'll see what is missing from the package.

**Comment by eikehein** [comment] 2015-05-14 19:51
> @eikehein : can you change kicker behaviour to not close the entire menu when choosing "forget all"? Just leave the main menu open and Recent greyed out, pretty much like if you click "forget this single item" if only one entry remains under Recent applications for example.

Sure, that's what I suggested - will do.

**Comment by eikehein** [comment] 2015-05-15 01:14
Patch to stop closing: http://commits.kde.org/plasma-desktop/140c3ab368c17234dd856765383464e664db7d50

**Comment by ivan-cukic** [comment] 2015-05-15 06:25
@apachelogger Can you add a new patch to plasma-desktop (09810d3df53b71cee923aedf7abe176f7b41b2ce from Plasma 5.3 branch)

**Comment by apachelogger** [comment] 2015-05-15 07:26
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-updates/+sourcepub/5068669/+listing-archive-extra

**Comment by star-buck** [comment] 2015-05-15 08:03
@apachelogger : both kikcer and plasma-desktop patches packaged?
@ivan-cukic : does this fix things?

**Comment by apachelogger** [comment] 2015-05-15 08:04
@star-buck yes

**Comment by ivan-cukic** [comment] 2015-05-15 08:16
@apachelogger Thanks
@star-buck It should work now properly - new kactivities and new plasma stuff. I'll be back later today (need to teach c++ to some students :) )

**Comment by star-buck** [comment] 2015-05-15 08:19
@ivan-cukic / @eikehein : both seem to work fine, thanks! 
will test some more for any side-effects, then close this.

**Closed** 2015-05-15 09:10 UTC
Labels: mid, packaged needs QA

**Comment by ivan-cukic** [comment] 2015-05-15 14:06
Cool. Thanks for testing @star-buck and for quick rebuilds @apachelogger :)

**Comment by star-buck** [comment] 2015-05-15 14:30
@ivan-cukic : the symlink doesnt seem to work though: https://github.com/blue-systems/plasma-5.4/issues/122
(I seperated that topic from the issue here)
