### ISSUE TITLE
[kio]: opening .mp3-file from folderview freezes desktop and returns error code on closing app

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.4#120] opened 2015-05-13 16:52 UTC
while testing out "open with" mimetypes, I noticed this:
https://www.dropbox.com/s/prx6e878asj4sv5/mp3-open-from-folderview.mkv?dl=0

**Comment by eikehein** [comment] 2015-05-13 16:57
Seems like a dupe of the old "running Kate from any launcher gets an error after" bug that turned out to be a badly crafted Kate .desktop file ... anyone remember the bug number?

**Comment by mck182** [comment] 2015-05-13 17:08
This is the patch that fixed kate with the discussion --> https://git.reviewboard.kde.org/r/122498/ -- in there dfaure also suggests to use "X-DBUS-StartupType=None" in the .desktop file.

**Comment by eikehein** [comment] 2015-05-13 17:17
@star-buck: can you attach the .desktop file for that music player?

**Comment by star-buck** [comment] 2015-05-13 17:36
well, its happening with any of those apps seen in the screencast: audacious, vlc player, gmusicplayer...

**Comment by eikehein** [comment] 2015-05-13 17:45
Thanks, I can reproduce it with VLC on Fedora. It doesn't happen in Dolphin (5), which is interesting since it should be the same library code producing both menus. Investigating.

**Comment by star-buck** [comment] 2015-05-13 18:17
does not seem to happen though if you simply click on file to open with default application, only when "open with"!

**Comment by eikehein** [comment] 2015-05-13 18:53
After an hour of chasing this through 10 levels of classes I'm slowly closing in on a bug in the desktop:// KIO slave dropping local URL schemes on the floor. You'll notice the problem goes away when you switch the FV config from "Show the desktop folder" to custom folder + explicit path to Desktop dir.

**Comment by eikehein** [comment] 2015-05-13 19:23
Patch up for review: https://git.reviewboard.kde.org/r/123781/

**Comment by star-buck** [comment] 2015-05-15 08:00
@apachelogger : lets ship and test in ci-updates.

**Comment by eikehein** [comment] 2015-05-16 12:57
Pushed: http://commits.kde.org/kio-extras/fe1f50caaf24c47000938c9ac36a7f9a304f3c96

**Comment by apachelogger** [comment] 2015-05-18 07:47
Apparently I forgot to post the URL. Sorry for that

https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-16-ci-updates/+sourcepub/5068703/+listing-archive-extra

**Closed** 2016-01-11 11:25 UTC
Labels: mid, ready -> needs QA
